### PR TITLE
Cleanup namespaces to make them more uniformly (see issue #19)

### PR DESCRIPTION
**Pull request by DLade**
Note:
This comes with a major version change because it is not backward compatible afterwards.

### CODE REVIEW

**Comment by DLade** [comment]
Be aware of the samples - as always I did not change them. You need to fix the dependencies there!

(If the samples would use "dotnet standard 2.0" I could fix them too ;-) )

**Comment by DLade** [comment]
I didn't rename ODATA yet ... do you think I should?

Suggestion "OData" (see http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#19).

**Comment by bertt** [comment]
yes OData looks ok to me!

I've migrated the ConsoleSampleApplication project to .NET Core 3.1 (https://github.com/gost/sensorthings-net-sdk/commit/7ef538a54ea7abe5b94a57fd8c6d2c007ab4148f)

**Comment by DLade** [comment]
Done, so far - OData and ConsoleSampleApplication are refactored.

**Pull request merged**
