### PR TITLE
Use Type instead of Enum.

### PR DESCRIPTION
**Pull request by DLade**

### CODE REVIEW

**Comment by bertt** [comment]
Hi,

I've tried the changes but could not build it:

. type.IsSubclassOf is not known. Probably because the library is .NET Standard 1.1 

After changing to .NET Standard 2.0 it compiles, but unit tests are failing. (Type by is null?) in Get<T>(Type get, Type by, string id, OdataQuery odata)

I think we should first upgrade the projects (using .NET Standard 2.0 for the library, .NET Core 3.1 for the unit tests.

**Comment by DLade** [comment]
Yes, I had the same problem, therefore I've changed the version temprary to .NET 3.1 and then back before creating the pull request.

Don't get confused about .NET Standard 1.1 - it is based on .NET 4.5 (see https://devblogs.microsoft.com/dotnet/introducing-net-standard/). But currently there is no newer version of .NET 3.1 for Linux - which is my problem then.

I'm currentliy working on a pull request for .NET 3.1 - used for sensorthings-net-sdk and it's tests.
There is no need for a newer .NET because we don't use any features of this.

**Comment by DLade** [comment]
Using .NET 3.1:
```
Test Run Failed.
Total tests: 29
     Passed: 24
     Failed: 5
 Total time: 13.9023 Seconds
```
I've got work to do ;-)

**Comment by DLade** [comment]
```
Test Run Successful.
Total tests: 29
     Passed: 29
 Total time: 17.1911 Seconds
```

**Comment by DLade** [comment]
Okay, I found out, that .NET Standard 2.0 should work with .NET Core 3.1 - therefore the problem is on my computer.
(see https://dotnet.microsoft.com/platform/dotnet-standard)

**Comment by DLade** [comment]
Test Run Successful.
Total tests: 29
     Passed: 29
 Total time: 19.7939 Seconds

**Comment by DLade** [comment]
```
$ dotnet test
...
Test Run Successful.
Total tests: 29
Passed: 29
Total time: 19.7939 Seconds
```

**Pull request merged**
